services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_rainfall
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - rainfall-network

  grafana:
    image: grafana/grafana
    container_name: grafana_rainfall
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${MAILGUN_HOST}
      - GF_SMTP_USER=${MAILGUN_EMAIL}
      - GF_SMTP_PASSWORD=${MAILGUN_PASSWORD}
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_NAME=grafana_rainfall
      - GF_SMTP_FROM_ADDRESS=${MAILGUN_EMAIL}
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
    networks:
      - rainfall-network

  node-exporter:
    container_name: node_exporter_rainfall
    image: prom/node-exporter:latest
    volumes:
      - ./node-exporter:/textfile_collector
    command:
      - '--collector.textfile.directory=/textfile_collector'
    ports:
      - "9100:9100"
    networks:
      - rainfall-network

volumes:
  prom_data:
  node-red-data:

networks:
  rainfall-network:
